"""final release

Revision ID: 59c0d463f723
Revises:
Create Date: 2023-01-13 15:59:54.011151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c0d463f723'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'service',
        'name',
        existing_type=sa.VARCHAR(),
        nullable=True
    )
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    op.alter_column(
        'servicekey',
        'version_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'servicekey',
        'service_key',
        existing_type=sa.VARCHAR(),
        nullable=True
    )
    op.alter_column(
        'servicekey',
        'service_value',
        existing_type=sa.VARCHAR(),
        nullable=True
    )
    op.create_index(
        op.f('ix_servicekey_id'), 'servicekey', ['id'], unique=False
    )
    op.drop_constraint('key_version_fk', 'servicekey', type_='foreignkey')
    op.create_foreign_key(
        None, 'servicekey',
        'serviceversion',
        ['version_id'],
        ['id']
    )
    op.alter_column(
        'serviceversion',
        'service_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'serviceversion',
        'version',
        existing_type=sa.VARCHAR(),
        nullable=True
    )
    op.alter_column(
        'serviceversion',
        'is_used',
        existing_type=sa.BOOLEAN(),
        nullable=True
    )
    op.create_index(
        op.f('ix_serviceversion_id'), 'serviceversion', ['id'], unique=False
    )
    op.drop_constraint(
        'version_service_fk', 'serviceversion', type_='foreignkey'
    )
    op.create_foreign_key(
        None, 'serviceversion', 'service', ['service_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serviceversion', type_='foreignkey')
    op.create_foreign_key(
        'version_service_fk',
        'serviceversion',
        'service',
        ['service_id'],
        ['id'],
        ondelete='CASCADE'
    )
    op.drop_index(op.f('ix_serviceversion_id'), table_name='serviceversion')
    op.alter_column(
        'serviceversion',
        'is_used',
        existing_type=sa.BOOLEAN(),
        nullable=False
    )
    op.alter_column(
        'serviceversion',
        'version',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    op.alter_column(
        'serviceversion',
        'service_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.drop_constraint(None, 'servicekey', type_='foreignkey')
    op.create_foreign_key(
        'key_version_fk',
        'servicekey',
        'serviceversion',
        ['version_id'],
        ['id'],
        ondelete='CASCADE'
    )
    op.drop_index(op.f('ix_servicekey_id'), table_name='servicekey')
    op.alter_column(
        'servicekey',
        'service_value',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    op.alter_column(
        'servicekey',
        'service_key',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    op.alter_column(
        'servicekey',
        'version_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.alter_column(
        'service',
        'name',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    # ### end Alembic commands ###
